export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTER_SCHOOL = 'REGISTER_SCHOOL';
export const GET_SCHOOL_DETAILS = 'GET_SCHOOL_DETAILS';
export const REGISTER_GUARDIAN = 'REGISTER_GUARDIAN';

export const GET_EVENT_TYPES= 'GET_EVENT_TYPES';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

export const GET_GUARDIANS = 'GET_GUARDIANS';
export const GET_GUARDIAN_DETAILS = 'GET_GUARDIAN_DETAILS';
export const UPDATE_GUARDIANS = 'UPDATE_GUARDIANS';